### ISSUE TITLE
Add function to detect if device is connected

### ISSUE THREAD

**Issue by eugene-y-mak** [MideTechnology/endaq-device#54]
Currently no easy way from what I can find to easily detect if any Endaq device is connected or not. In the past, it seems I've used a try-catch with getting the first element of getting a list of connected devices, but would be nice to have it officially implemented through a more robust way.

**Comment by StokesMIDE** [comment]
Do you mean a way of detecting if a specific `Recorder` object (e.g. one gotten via `getDevices()`) is still plugged in? There's actually an issue regarding that on our internal Jira, but it hadn't made it over (it was part of another project). This is the issue:

> It would be useful to have a feature to wait for a device to reappear (after rebooting or recording). Proposed:
> * `Recorder.available` (property, RO): Indicates the recorder is attached as a storage device.
> * `CommandInterface.awaitReconnect()`: Like the existing `awaitReboot()`, but waits for the device to be present rather than absent.
> 
> It might also be good to have a `CommandInterface.available` property, in preparation for devices that aren’t local storage devices, or an extra safe way to identify the device is present.

**Comment by eugene-y-mak** [comment]
Yes, I think essentially that's what I'm interested in. Right now I'm working on a timing drift test script, which requires validating the device is still plugged in before each timing drift recording. Something like to `Recorder.available` sounds pretty useful to use for that, where I could check that property to ensure the device I'm testing is still connected/available.

**Comment by StokesMIDE** [comment]
Will be in release 1.0.8, PR #65
